const users=[
    {
        id:1,
        name:"vardhan",
        email:"vardahn@gmail.com"
    },
    {
        id:2,
        name:"smith",
        email:"smith@gmail.com"
    },
    {
        id:3,
        name:"jack",
        email:"jack@gmail.com"
    },
    {
        id:4,
        name:"chris",
        email:"chris@gmail.com"
    },
]
module.exports=users;